### ISSUE TITLE
Add sizing details to the site.

### ISSUE THREAD

**Issue by natanialeclerc** [thinkshout/pear#10]
## Overview
Currently no information on the sizing of the shirts. We need to specify that they are unisex, and the measurements of each size (see attached image).
![shirt sizing](https://user-images.githubusercontent.com/17132124/29046249-74ccc0e6-7b7b-11e7-8f63-a32139848798.png)

## This ticket is done when:
- [ ] item
- [ ] item

**Comment by khirsch** [comment]
Resolved.
