### ISSUE TITLE
Initial code push of the Jekyll build

### ISSUE THREAD

**Issue by mariacha** [thinkshout/pear#2]
## Dev [8hrs]
- [x] Build a new Jekyll site locally
- [x] Decide which files should be committed based on Thinkshout's repo https://github.com/thinkshout/thinkshout
- [x] Add the files to the github repo
- [x] Add documentation for how to build the site locally (for other devs)
- [x] Create "Hello P:ear" page. Be as creative as you like.

## Theme [4 hrs]
- [x] Get Sass installed
- [x] Pick a CSS framework
- [x] See if jQuery is needed and install as needed.

## This ticket is done when:
- [x] Another dev can clone this repo, follow the instructions to run the site locally, and sees a Hello P:ear page

**Comment by myishakinberg** [comment]
All of the dev work has been completed as of now. Katrina is still working on installing Sass and picking a CSS framework.

**Comment by khirsch** [comment]
It seems Jekyll already has a built-in Sass compiler, so that's taken care of. Going with Bulma as a framework, at least for now.
