### ISSUE TITLE
social icons hover line

### ISSUE THREAD

**Issue by levelos** [thinkshout/pear#5]
## Overview
Underline appears when hovering over social media icons in footer.
![image](https://user-images.githubusercontent.com/104897/28950446-c83dca28-7878-11e7-8c1d-aab3e54e1279.png)

## This ticket is done when:
- [x] There is no line that appears when hovering.

**Comment by khirsch** [comment]
Weird line removed and animation added to the icons to make them pop out (literally) a little more.
